### PR TITLE
feat: use `atlas` in `make pull_translations`

### PR DESCRIPTION
**Pull request by OmarIthawi**
## Changes

Install [`openedx-atlas`](https://github.com/openedx/openedx-atlas/#readme) as an alternative to Transifex `tx` client for managing translations when `OPENEDX_ATLAS_PULL` environment variable is set. This is similar to the [discovery atlas pull request](https://github.com/openedx/course-discovery/pull/4037).

### Testing

 - [x] Install atlas via `pip-tools`, but undo other packages upgrade to simulate `pip-tools --upgrade-package=openedx-atlas`
 - [x] Build the docker image
```
# Credentials repo
cd ~/work/openedx/credentials
docker build --target=dev -t edxops/credentials:latest .

# Devstack
cd ~/work/openedx/devstack
make dev.remove-containers.credentials
make dev.up.credentials

# Similar to `make dev.shell.credentials` but with custom commands
docker-compose exec credentials atlas --version
docker-compose exec credentials env OPENEDX_ATLAS_PULL=true make pull_translations static.dev
docker-compose exec credentials ls -R credentials/conf

# Reset the credentials container to the upstream image from Docker Hub
docker pull edxops/credentials:latest

# Get into the shell for manual testing
make dev.shell.credentials
```

 - [x] run `OPENEDX_ATLAS_PULL=true make pull_translations static.dev`

```
$ docker-compose exec credentials ls -R credentials/conf

credentials/conf:
locale

credentials/conf/locale:
config.yaml  en  fr_CA

credentials/conf/locale/en:
LC_MESSAGES

credentials/conf/locale/en/LC_MESSAGES:
djangojs.mo  djangojs.po  django.mo  django.po

credentials/conf/locale/fr_CA:
LC_MESSAGES

credentials/conf/locale/fr_CA/LC_MESSAGES:
djangojs.mo  djangojs.po  django.mo  django.po

```

 - [x] Test translations locally in devstack
<kbd>image</kbd>

**Run JavaScript tests locally with Karma**

There is work being done on a fix to get Karma to run in CI. Until then, however, contributors are required to run these tests locally.

- [x] Make sure you are inside the devstack container
- [x] Run `make test-karma`
- [ ] All tests pass

```sh
# Replicate `make test-karma`
$ make dev.shell.credentials
# Inside the shell
$ apt update -y
$ apt install --no-install-recommends -y firefox xvfb
$ xvfb-run ./node_modules/.bin/karma start
```

Tests doesn't work with the `credentials/Dockefile` repo, so I'm assuming this is something specific to the [`configuration`-based](https://github.com/openedx/configuration/blob/473a9faa3490fd7a9589e7a48e9e5423010fc69a/docker/build/credentials/Dockerfile) Dockerfile build.

References
----------

This contribution is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which is sparked by the [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).

Up-to-date project overview and details are available in the [Approach Memo and Technical Discovery: Translations Infrastructure Implementation](https://docs.google.com/document/d/11dFBCnbdHiCEdZp3pZeHdeH8m7Glla-XbIin7cnIOzU/edit#) document.

Join the conversation on [Open edX Slack #translations-project-fc-0012](https://openedx.slack.com/archives/C04R6TUJB7T).

Check the links above for full information about the overall project.

Internalization is being rearchitected in Open edX Python, XBlock, Micro-frontend, and other projects. There are a number of immediately visible changes:
 - Remove source and language translations from the repositories, hence no `.json`, `.po` or `.mo` files will be committed into the repos.
 - Add standardized `make extract_translations` in all repositories
 - Push user-facing messages strings into [openedx/openedx-translations](https://github.com/openedx/openedx-translations/).
 - Integrate root repositories with [openedx/openedx-atlas](https://github.com/openedx/openedx-atlas/) to pull translations on build/deploy time

Breaking Changes
----------------

One of the primary goals of the project is to **avoid breaking changes**. If you noticed any suspicious code, please raise your concern.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @OmarIthawi!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by OmarIthawi** [comment]
@openedx/2U-aperture @brian-smith-tcril this is ready for review and merge. Similar to the This is similar to the https://github.com/openedx/course-discovery/pull/4037 discovery pull request.

**Review by brian-smith-tcril — APPROVED** [review]

**Comment by brian-smith-tcril** [comment]
@openedx/2u-aperture you are listed as "Please inform:" on the OEP-58 repo reviewers spreadsheet. If there is no opposition I will merge this the morning of Wednesday, September 20th.

**Comment by jsnwesson** [comment]
Very exciting! Thanks for the inform. Is the environment variable expected to be set immediately after this is merged?

**Comment by OmarIthawi** [comment]
> Very exciting! Thanks for the inform. Is the environment variable expected to be set immediately after this is merged?

@jsnwesson Good question! In short, no. We plan to enable the environment variable sometimes later. The exact timeline isn't known yet. However, you're welcome to enable it immediately on staging to help us testing it 😅

**Comment by jsnwesson** [comment]
I should've been clearer, but there is no opposition on the Aperture side!

**Comment by OmarIthawi** [comment]
Thanks @jsnwesson!! Have a good one :)

@brian-smith-tcril This should be ready for merge.

**Comment by openedx-webhooks** [comment]
@OmarIthawi 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/credentials&entry.867055334=https://github.com/openedx/credentials/pull/2153&entry.1484655318=https://github.com/OmarIthawi&entry.752974735=2023-08-31+10:01&entry.1917517419=2023-09-21+16:05&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
