### PR TITLE
Paragon StatusAlert deprecation

### PR DESCRIPTION
**Pull request by abdullahwaheed**
### Ticket
[Migrate off deprecated Paragon components](https://github.com/openedx/frontend-wg/issues/102)

### What has changed
Removed deprecated `StatusAlert` component of paragon and updated it with `Alert`

### References
[Paragon StatusAlert](https://paragon-openedx.netlify.app/components/statusalert/)
[Paragon Alert](https://paragon-openedx.netlify.app/components/alert/)

### CODE REVIEW

**Review by davidjoy — APPROVED** [review]
This seems like a fine change - the owning team should also review so they're aware of the change, it should be tested by Fed-BOM and we can get it in.  I did a cursory review.

**Comment by justinhynes** [comment]
Screenshots before and after the change...

Before
image

After
image

**Review by justinhynes — CHANGES_REQUESTED** [review]
Changes look good, I checked it locally and noticed that the `Dismiss` button text seems larger than expected. It seems very large compared to the examples from Paragon.  Is there anyway to adjust that?

**Comment by justinhynes** [comment]
@abdullahwaheed -- quick question on the size of the Dismiss button before accepting this change. Thanks for the help and let me know what you think!

**Comment by abdullahwaheed** [comment]
@justinhynes `.btn` styling was affecting its font, removed this to make it consistent with library

**Comment by justinhynes** [comment]
I think this change is also having conflicts with the `edx.org` theme. :(

In the `openedx` theme the button size looks right:
image

In the `edx.org` theme the button size is unchanged:
image

Sorry :(

**Comment by justinhynes** [comment]
@abdullahwaheed Is this ready for another look too? Or is this still being worked on?

**Comment by abdullahwaheed** [comment]
@justinhynes need some changes from #1691. Will update it once its merged

**Comment by abdullahwaheed** [comment]
@justinhynes its ready for review, kindly test it again

**Comment by justinhynes** [comment]
@abdullahwaheed I am still seeing a button size discrepancy between the `openedx` and `edx.org` themes:

`openedx`:
image

`edx.org`:
image

**Comment by abdullahwaheed** [comment]
I have tested it on `edx.org` theme and override styles are working. 
image

**Comment by justinhynes** [comment]
@abdullahwaheed Thanks for the update. Something might not quite be right in my local environment. Based on your screenshots I think this is good to go.

**Review by justinhynes — APPROVED** [review]

**Pull request merged**
