### PR TITLE
refactor: Paragon modal component deprecation

### PR DESCRIPTION
**Pull request by Mashal-m**
### Ticket

[Migrate off deprecated Paragon components](https://github.com/openedx/frontend-wg/issues/102)

Migrate off deprecated paragon component in ShareProgramRecordModal andSendLearnerRecordModal files.

### Share Program Modal Before
Screenshot 2022-10-07 at 10 33 14 AM

### Share Program Modal After

share link after

### Send Learner Modal Before

Edx Cred before

### Share Program Modal after

Edx Cred after

### CODE REVIEW

**Comment by hurtstotouchfire** [comment]
Hi guys, this UI is deprecated: https://github.com/openedx/credentials/issues/1722
Since the old UI won't be removed until spring we should maybe still merge this though. I'm conferring with the team about when we could merge this.

**Comment by hurtstotouchfire** [comment]
@arbrandes Do you think we need to prioritize this? I don't yet know of anyone who falls into the mysterious set of operators who might be using Credentials without Tutor support, and when Tutor support comes along it will coincide with this UI being deleted.

**Comment by arbrandes** [comment]
@hurtstotouchfire, @abdullahwaheed, @Mashal-m, are we closing this one then?  As in, no more updates to the deprecated credentials UI?

**Comment by Mashal-m** [comment]
> @hurtstotouchfire, @abdullahwaheed, @Mashal-m, are we closing this one then? As in, no more updates to the deprecated credentials UI?

Yes, I am closing this. As per the discussion in the last meeting, we are not proceeding with this Repo anymore and this UI is also going to be deprecated.

**Pull request closed without merging**
