### PR TITLE
feat: [FC-0006] add Verifiable Credentials optional feature

### PR DESCRIPTION
**Pull request by wowkalucky**
**Note:**  for the sake of review effort simplification, it is decided to split this large PR onto 2 parts: 
- initial part - introduces a feature flag with a new application modules structure
- main part - adds all the implementation logic

This is the part 1/2 of the Verifiable Credentials feature.

Related PRs:

- [2nd part](https://github.com/openedx/credentials/pull/2001)
- [documentation](https://github.com/openedx/credentials/pull/1991)
- [configuration](https://github.com/openedx/configuration/pull/6928)

----

**Run JavaScript tests locally with Karma**

There is work being done on a fix to get Karma to run in CI. Until then, however, contributors are required to run these tests locally.

- [x] Make sure you are inside the devstack container
- [x] Run `make test-karma`
- [x] All tests pass

---

- Relates to https://github.com/openedx/frontend-app-learner-record/pull/151

## TODO

- [x] - add related Open edX Credentials PR link.
- [x] - update test coverage

### CODE REVIEW

**Comment by e0d** [comment]
@wowkalucky confirming this should still be in draft?

**Comment by wowkalucky** [comment]
@e0d coverage is almost there. Moved for review.
The Verifiable Credentials documentation is a matter of a separate PR.

**Comment by wowkalucky** [comment]
@e0d we increased patch coverage now. Should we proceed to reach the overall project's target value in this PR?

**Comment by mphilbrick211** [comment]
Hi @AliAdnanSohail - would you mind taking a look at this and merging if all looks good? Thanks!

**Comment by mphilbrick211** [comment]
> Hi @AliAdnanSohail - would you mind taking a look at this and merging if all looks good? Thanks!

Hi @AliAdnanSohail - I tagged you by mistake, so please disregard - no need to review this PR.

**Comment by openedx-webhooks** [comment]
@wowkalucky 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/credentials&entry.867055334=https://github.com/openedx/credentials/pull/1973&entry.1484655318=https://github.com/wowkalucky&entry.752974735=2023-03-27+16:17&entry.1917517419=2023-05-23+14:24&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
