### PR TITLE
feat: Backport adding Badge issuance to Redwood

### PR DESCRIPTION
**Pull request by KyryloKireiev**
This is backport of the commit https://github.com/openedx/credentials/commit/da22842e7d1287bf61bd819e718a4da437db9e42 to redwood.master

Original PR: https://github.com/openedx/credentials/pull/2489

Description:
This pull request implements https://github.com/openedx/platform-roadmap/issues/280 feature.

Changes:

Creates new badges application.
Extends documentation with badges section.
Extends set of credentials
Related documentation:
See temporarily deployed documentation https://raccoongang.github.io/credentials/badges/index.html

Related PR's:

https://github.com/openedx/openedx-events/pull/303
https://github.com/openedx/edx-platform/pull/34749

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @KyryloKireiev!

### What's next?

*Please work through the following steps to get your changes ready for engineering review:*

#### :radio_button: Get product approval

If you haven't already, [check this list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Does-my-contribution-require-Product-Review%3F) to see if your contribution needs to go through the product review process.

- If it does, you'll need to submit a product proposal for your contribution, and have it reviewed by the [Product Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3449028609/Product+Working+Group).
    - This process (including the steps you'll need to take) is documented [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process).
- If it doesn't, simply proceed with the next step.

#### :radio_button: Provide context

To help your reviewers and other members of the community understand the purpose and larger context of your changes, feel free to add as much of the following information to the PR description as you can:

- Dependencies
  > This PR must be merged before / after / at the same time as ...
- Blockers
  > This PR is waiting for OEP-1234 to be accepted.
- Timeline information
  > This PR must be merged by XX date **because** ...
- Partner information
  > This is for a course on edx.org.
- Supporting documentation
- Relevant [Open edX discussion forum](https://discuss.openedx.org/) threads





#### :radio_button: Get a green build

If one or more checks are failing, continue working on your changes until this is no longer the case and your build turns green.



#### :radio_button: Let us know that your PR is ready for review:

### Who will review my changes?


This repository is currently maintained by `@2U-aperture`.  Tag them in a comment and let them know that your changes are ready for review.


### Where can I find more information?

If you'd like to get more details on all aspects of the review process for open source pull requests (OSPRs), check out the following resources:

- [Overview of Review Process for Community Contributions](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/FAQ-about-pull-requests.html)
- [Pull Request Status Guide](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/pull-request-statuses.html)
- [Making changes to your pull request](https://docs.openedx.org/en/latest/documentors/how-tos/make_changes_to_your_pull_request.html)

### When can I expect my changes to be merged?

Our goal is to get community contributions seen and reviewed as efficiently as possible.

However, the amount of time that it takes to review and merge a PR can vary significantly based on factors such as:

- The size and impact of the changes that it introduces
- The need for product review
- Maintenance status of the parent repository

:bulb: *As a result it may take up to several weeks or months to complete a review and merge your PR.*

**Review by deborahgu — CHANGES_REQUESTED** [review]
👀

**Comment by deborahgu** [comment]
[I asked a question about this on discourse](https://discuss.openedx.org/t/backport-should-we-merge-backport-of-badge-issuance/13542). I would love if you contributed to talk about why you want the backport.  I just want to get signoff from the larger community for a large feature backport.

**Comment by cmltaWt0** [comment]
Decided to not backport it to the Redwood release.

**Comment by mboisson** [comment]
I know I am late on the party here, but currently looking at implementing badges. Canvas Badge (Badgr) seemed like a good free option, but Credly (which seems to be the next supported option) is very costly. Is there a way to keep Badgr support, either through a plugin or extension ? We are using Redwood, but will be upgrading in the future too.

**Pull request closed without merging**
