### PR TITLE
feat: [FC-0006] add plugins support

### PR DESCRIPTION
**Pull request by wowkalucky**
**Run JavaScript tests locally with Karma**

There is work being done on a fix to get Karma to run in CI. Until then, however, contributors are required to run these tests locally.

- [x] Make sure you are inside the devstack container
- [x] Run `make test-karma`
- [x] All tests pass

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @wowkalucky!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by justinhynes** [comment]
Hi @wowkalucky. Sorry for the delay. I just wanted to add that I am going to try to start taking a look at this today but most likely will focus on reviewing this PR Monday, March 6th. Just wanted to keep you on the loop and let you know that it's on my plate.

**Review by justinhynes — APPROVED** [review]
These changes track with the available documentation. LGTM. Thanks for your patience!

**Comment by mphilbrick211** [comment]
Hi @hurtstotouchfire @justinhynes if this looks good to you, could one of you please merge? Thanks!

**Pull request merged**
